runtime: python39
entrypoint: gunicorn -w 1 -k uvicorn.workers.UvicornWorker app.main:app --host=0.0.0.0 --port=8080

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  PORT: "8080"
