runtime: python39
entrypoint: uvicorn app.main:app --host=0.0.0.0 --port=8080

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65s
  min_instances: 1
  max_instances: 5

env_variables:
  PORT: "8000"
